package org.jhipster.projectintern.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AuthentificationConfigurationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuthentificationConfigurationAllPropertiesEquals(
        AuthentificationConfiguration expected,
        AuthentificationConfiguration actual
    ) {
        assertAuthentificationConfigurationAutoGeneratedPropertiesEquals(expected, actual);
        assertAuthentificationConfigurationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuthentificationConfigurationAllUpdatablePropertiesEquals(
        AuthentificationConfiguration expected,
        AuthentificationConfiguration actual
    ) {
        assertAuthentificationConfigurationUpdatableFieldsEquals(expected, actual);
        assertAuthentificationConfigurationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuthentificationConfigurationAutoGeneratedPropertiesEquals(
        AuthentificationConfiguration expected,
        AuthentificationConfiguration actual
    ) {
        assertThat(expected)
            .as("Verify AuthentificationConfiguration auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuthentificationConfigurationUpdatableFieldsEquals(
        AuthentificationConfiguration expected,
        AuthentificationConfiguration actual
    ) {
        assertThat(expected)
            .as("Verify AuthentificationConfiguration relevant properties")
            .satisfies(e -> assertThat(e.getTwoFactorEnabled()).as("check twoFactorEnabled").isEqualTo(actual.getTwoFactorEnabled()))
            .satisfies(
                e ->
                    assertThat(e.getLoginPageCustomization())
                        .as("check loginPageCustomization")
                        .isEqualTo(actual.getLoginPageCustomization())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuthentificationConfigurationUpdatableRelationshipsEquals(
        AuthentificationConfiguration expected,
        AuthentificationConfiguration actual
    ) {
        assertThat(expected)
            .as("Verify AuthentificationConfiguration relationships")
            .satisfies(e -> assertThat(e.getHotel()).as("check hotel").isEqualTo(actual.getHotel()));
    }
}
