package org.jhipster.projectintern.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HotelAdministrateurAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHotelAdministrateurAllPropertiesEquals(HotelAdministrateur expected, HotelAdministrateur actual) {
        assertHotelAdministrateurAutoGeneratedPropertiesEquals(expected, actual);
        assertHotelAdministrateurAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHotelAdministrateurAllUpdatablePropertiesEquals(HotelAdministrateur expected, HotelAdministrateur actual) {
        assertHotelAdministrateurUpdatableFieldsEquals(expected, actual);
        assertHotelAdministrateurUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHotelAdministrateurAutoGeneratedPropertiesEquals(HotelAdministrateur expected, HotelAdministrateur actual) {
        assertThat(expected)
            .as("Verify HotelAdministrateur auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHotelAdministrateurUpdatableFieldsEquals(HotelAdministrateur expected, HotelAdministrateur actual) {
        assertThat(expected)
            .as("Verify HotelAdministrateur relevant properties")
            .satisfies(e -> assertThat(e.getNom()).as("check nom").isEqualTo(actual.getNom()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getMotDePasse()).as("check motDePasse").isEqualTo(actual.getMotDePasse()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHotelAdministrateurUpdatableRelationshipsEquals(HotelAdministrateur expected, HotelAdministrateur actual) {}
}
