package org.jhipster.projectintern.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PartenaireAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartenaireAllPropertiesEquals(Partenaire expected, Partenaire actual) {
        assertPartenaireAutoGeneratedPropertiesEquals(expected, actual);
        assertPartenaireAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartenaireAllUpdatablePropertiesEquals(Partenaire expected, Partenaire actual) {
        assertPartenaireUpdatableFieldsEquals(expected, actual);
        assertPartenaireUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartenaireAutoGeneratedPropertiesEquals(Partenaire expected, Partenaire actual) {
        assertThat(expected)
            .as("Verify Partenaire auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartenaireUpdatableFieldsEquals(Partenaire expected, Partenaire actual) {
        assertThat(expected)
            .as("Verify Partenaire relevant properties")
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getNom()).as("check nom").isEqualTo(actual.getNom()))
            .satisfies(e -> assertThat(e.getContact()).as("check contact").isEqualTo(actual.getContact()))
            .satisfies(e -> assertThat(e.getAdresse()).as("check adresse").isEqualTo(actual.getAdresse()))
            .satisfies(e -> assertThat(e.getTypePartenaire()).as("check typePartenaire").isEqualTo(actual.getTypePartenaire()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartenaireUpdatableRelationshipsEquals(Partenaire expected, Partenaire actual) {
        assertThat(expected)
            .as("Verify Partenaire relationships")
            .satisfies(e -> assertThat(e.getService()).as("check service").isEqualTo(actual.getService()));
    }
}
