package org.jhipster.projectintern.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static org.jhipster.projectintern.domain.AssertUtils.zonedDataTimeSameInstant;

public class ReservationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservationAllPropertiesEquals(Reservation expected, Reservation actual) {
        assertReservationAutoGeneratedPropertiesEquals(expected, actual);
        assertReservationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservationAllUpdatablePropertiesEquals(Reservation expected, Reservation actual) {
        assertReservationUpdatableFieldsEquals(expected, actual);
        assertReservationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservationAutoGeneratedPropertiesEquals(Reservation expected, Reservation actual) {
        assertThat(expected)
            .as("Verify Reservation auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservationUpdatableFieldsEquals(Reservation expected, Reservation actual) {
        assertThat(expected)
            .as("Verify Reservation relevant properties")
            .satisfies(
                e ->
                    assertThat(e.getDateDebut())
                        .as("check dateDebut")
                        .usingComparator(zonedDataTimeSameInstant)
                        .isEqualTo(actual.getDateDebut())
            )
            .satisfies(
                e -> assertThat(e.getDateFin()).as("check dateFin").usingComparator(zonedDataTimeSameInstant).isEqualTo(actual.getDateFin())
            )
            .satisfies(e -> assertThat(e.getTotalPrix()).as("check totalPrix").isEqualTo(actual.getTotalPrix()))
            .satisfies(e -> assertThat(e.getStatutPaiement()).as("check statutPaiement").isEqualTo(actual.getStatutPaiement()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservationUpdatableRelationshipsEquals(Reservation expected, Reservation actual) {
        assertThat(expected)
            .as("Verify Reservation relationships")
            .satisfies(e -> assertThat(e.getHotel()).as("check hotel").isEqualTo(actual.getHotel()));
    }
}
