package org.jhipster.projectintern.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ServiceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceAllPropertiesEquals(Service expected, Service actual) {
        assertServiceAutoGeneratedPropertiesEquals(expected, actual);
        assertServiceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceAllUpdatablePropertiesEquals(Service expected, Service actual) {
        assertServiceUpdatableFieldsEquals(expected, actual);
        assertServiceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceAutoGeneratedPropertiesEquals(Service expected, Service actual) {
        assertThat(expected)
            .as("Verify Service auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceUpdatableFieldsEquals(Service expected, Service actual) {
        assertThat(expected)
            .as("Verify Service relevant properties")
            .satisfies(e -> assertThat(e.getNom()).as("check nom").isEqualTo(actual.getNom()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getPrix()).as("check prix").isEqualTo(actual.getPrix()))
            .satisfies(e -> assertThat(e.getDisposability()).as("check disposability").isEqualTo(actual.getDisposability()))
            .satisfies(e -> assertThat(e.getCapacite()).as("check capacite").isEqualTo(actual.getCapacite()))
            .satisfies(e -> assertThat(e.getTypeService()).as("check typeService").isEqualTo(actual.getTypeService()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceUpdatableRelationshipsEquals(Service expected, Service actual) {
        assertThat(expected)
            .as("Verify Service relationships")
            .satisfies(e -> assertThat(e.getHotel()).as("check hotel").isEqualTo(actual.getHotel()))
            .satisfies(e -> assertThat(e.getPartenaire()).as("check partenaire").isEqualTo(actual.getPartenaire()))
            .satisfies(e -> assertThat(e.getReservation()).as("check reservation").isEqualTo(actual.getReservation()));
    }
}
