package org.jhipster.projectintern.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static org.jhipster.projectintern.domain.AssertUtils.zonedDataTimeSameInstant;

public class UIConfigurationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUIConfigurationAllPropertiesEquals(UIConfiguration expected, UIConfiguration actual) {
        assertUIConfigurationAutoGeneratedPropertiesEquals(expected, actual);
        assertUIConfigurationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUIConfigurationAllUpdatablePropertiesEquals(UIConfiguration expected, UIConfiguration actual) {
        assertUIConfigurationUpdatableFieldsEquals(expected, actual);
        assertUIConfigurationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUIConfigurationAutoGeneratedPropertiesEquals(UIConfiguration expected, UIConfiguration actual) {
        assertThat(expected)
            .as("Verify UIConfiguration auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUIConfigurationUpdatableFieldsEquals(UIConfiguration expected, UIConfiguration actual) {
        assertThat(expected)
            .as("Verify UIConfiguration relevant properties")
            .satisfies(e -> assertThat(e.getColorSchema()).as("check colorSchema").isEqualTo(actual.getColorSchema()))
            .satisfies(e -> assertThat(e.getLogo()).as("check logo").isEqualTo(actual.getLogo()))
            .satisfies(e -> assertThat(e.getBanner()).as("check banner").isEqualTo(actual.getBanner()))
            .satisfies(
                e ->
                    assertThat(e.getDateCreation())
                        .as("check dateCreation")
                        .usingComparator(zonedDataTimeSameInstant)
                        .isEqualTo(actual.getDateCreation())
            )
            .satisfies(
                e ->
                    assertThat(e.getDateModify())
                        .as("check dateModify")
                        .usingComparator(zonedDataTimeSameInstant)
                        .isEqualTo(actual.getDateModify())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUIConfigurationUpdatableRelationshipsEquals(UIConfiguration expected, UIConfiguration actual) {
        assertThat(expected)
            .as("Verify UIConfiguration relationships")
            .satisfies(e -> assertThat(e.getHotel()).as("check hotel").isEqualTo(actual.getHotel()));
    }
}
