package org.jhipster.projetintern.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static org.jhipster.projetintern.domain.AssertUtils.zonedDataTimeSameInstant;

public class EmailTemplateConfigurationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailTemplateConfigurationAllPropertiesEquals(
        EmailTemplateConfiguration expected,
        EmailTemplateConfiguration actual
    ) {
        assertEmailTemplateConfigurationAutoGeneratedPropertiesEquals(expected, actual);
        assertEmailTemplateConfigurationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailTemplateConfigurationAllUpdatablePropertiesEquals(
        EmailTemplateConfiguration expected,
        EmailTemplateConfiguration actual
    ) {
        assertEmailTemplateConfigurationUpdatableFieldsEquals(expected, actual);
        assertEmailTemplateConfigurationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailTemplateConfigurationAutoGeneratedPropertiesEquals(
        EmailTemplateConfiguration expected,
        EmailTemplateConfiguration actual
    ) {
        assertThat(expected)
            .as("Verify EmailTemplateConfiguration auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailTemplateConfigurationUpdatableFieldsEquals(
        EmailTemplateConfiguration expected,
        EmailTemplateConfiguration actual
    ) {
        assertThat(expected)
            .as("Verify EmailTemplateConfiguration relevant properties")
            .satisfies(e -> assertThat(e.getNomTemplate()).as("check nomTemplate").isEqualTo(actual.getNomTemplate()))
            .satisfies(e -> assertThat(e.getCorps()).as("check corps").isEqualTo(actual.getCorps()))
            .satisfies(
                e ->
                    assertThat(e.getDateCreation())
                        .as("check dateCreation")
                        .usingComparator(zonedDataTimeSameInstant)
                        .isEqualTo(actual.getDateCreation())
            )
            .satisfies(
                e ->
                    assertThat(e.getDateModify())
                        .as("check dateModify")
                        .usingComparator(zonedDataTimeSameInstant)
                        .isEqualTo(actual.getDateModify())
            )
            .satisfies(e -> assertThat(e.getActiveStatus()).as("check activeStatus").isEqualTo(actual.getActiveStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailTemplateConfigurationUpdatableRelationshipsEquals(
        EmailTemplateConfiguration expected,
        EmailTemplateConfiguration actual
    ) {
        assertThat(expected)
            .as("Verify EmailTemplateConfiguration relationships")
            .satisfies(e -> assertThat(e.getHotel()).as("check hotel").isEqualTo(actual.getHotel()));
    }
}
